export const defaultCommonStateFill = {
  fillStatus: false,
  fillBrand: false,
  fillForm: false,
  fillDate: false,
  fillNumberB: false,
  fillFuel: false,
  fillCountry: false,
  fillModel: false,
  fillSit: false,
  fillColor: false,
  fillCarN: false,
  fillOwner: false,
  fillAcces: false,
  fillRegis: false,
  fillPrice: false,
  fillKm: false,
  fillTitle: false,
  fillIntro: false,
  fillYouR: false,
  fillAddress: false,
  stateFill: false,
};
