export const defaultCommonState = {
  value: "",
  color: "",
  carNumber: "",
  owner: "",
  country: "",
  sit: "",
  activeButton: "",
  accessories: "",
  registry: "",
  numberBox: "",
  dateCar: "",
  status: "",
  form: "",
  price: 0,
  km: 0,
  models: [],
  model: "",
};
