export const defaultCommonState = {
  value: "",
  color: "",
  carNumber: "",
  owner: "",
  country: "",
  sit: "",
  activeButton: "",
  accessories: "",
  registry: "",
  numberBox: "",
  dateCar:"",
  status: "",
  form: "",
  price: "",
  km: "",
  models: [],
  model: "",
};
