export const defaultCommonState = {
  modalConfirmSwitchFav: false,
  modalConfirmSwitch: false,
  modalConfirmSwitchCCCD: false,
  dateCCCD: "",
  fullName: "",
  cccd: "",
  location: "",
  cityValue: "",
  introducing: "",
  districtValue: "",
  wardValue: "",
  sex: "",
  birth: "",
  selectedItemFav: [],
  numberFax: "",
  rememberName: "",
  detailAddress: "",
  fullCCCD: "",
  fullFav: [],
  fullAddress: "",
  cities: [],
  districts: [],
  wards: [],
  activeIndices: [],
};
