export const defaultCommonState = {
  searchResult: [],
  cities: [],
  districts: [],
  searchResultDistrict: "",
  cityName: "",
  districtName: "",
  selectCity: "",
  valueRadioSit: "",
  valueRadioBrand: "",
  valueRadio: "",
  valueRadioDistrict: "",
  openSearchCity: false,
  openSearchDistrict: false,
  openFind: false,
  openPrice: false,
  openSit: false,
  openBrand: false,
};
